### ISSUE TITLE
base-noprelude doesn't support base 4.14

### ISSUE THREAD

**Issue by galagora** [tek/polysemy-http#1]
As a result, this package doesn't work with GHC 8.10. Why not just use `NoImplicitPrelude`?

**Comment by tek** [comment]
couple of points:

* there is a local custom `Prelude` module that replaces the regular one
* `ghci` has many problems with prelude shenanigans, this is the only configuration that I got working for all requirements
  I tried this:
  ```yaml
  - name: base
    mixin:
      - hiding (Prelude)
  ```
  which should work in my view, but `ghci` still gets confused
* this package doesn't compile with 8.10 at all because of a GHC panic caused by `polysemy-plugin`
* the build up to the compile error works for me with 8.10

any suggestions? :laughing:

**Comment by tek** [comment]
I think I found a way. give me a minute.

**Comment by tek** [comment]
righto, I've changed the way ghci deals with Prelude and it now works with using the mixin!
on top, I made cabal use `-O1` when compiling with 8.10, so that should work now as well!

**Comment by galagora** [comment]
Great. Let me try compiling...

**Comment by tek** [comment]
made a hackage release

**Comment by tek** [comment]
thanks a lot for the nudge, this is a way more comfortable setup! now to change all my other projects to use it…
